### ISSUE TITLE
Autoupdate function

### ISSUE THREAD

**Issue by derneuere** [guysoft/LibrePhotosOS#5]
The current setup is based on docker-compose. It would be great if there was a cronjob or script to download the latest containers and prune the old ones.

**Comment by guysoft** [comment]
There is already a systemd service that does this in stable:
https://github.com/guysoft/CustomPiOS/blob/devel/src/modules/docker/filesystem/root/etc/systemd/system/docker-compose.service

Its code:
https://github.com/guysoft/CustomPiOS/blob/devel/src/modules/docker/filesystem/root/usr/bin/start_docker_compose


IMHO systemd is way better than cron because you can debug the output, it knows when to start (eg after the network) and there is a standard way to enable/disable/start/stop it.

**Comment by derneuere** [comment]
Thanks for the clarification!
